/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : SystemTick.h
**     Project     : v40.4.5.7_IN3UP
**     Processor   : MCF52233CAF60
**     Component   : FreeCntr32
**     Version     : Component 02.070, Driver 01.05, CPU db: 3.00.000
**     Compiler    : CodeWarrior MCF C Compiler
**     Date/Time   : 2026-06-11, 12:54, # CodeGen: 13
**     Abstract    :
**         This device "FreeCntr32" implements 32-bit Free Running Counter
**     Settings    :
**         Timer name                  : PIT0 (16-bit)
**         Compare name                : PIT0_Modulus
**         Counter shared              : No
**
**         High speed mode
**             Prescaler               : divide-by-1
**             Clock                   : 29491200 Hz
**           Resolution of timer
**             Xtal ticks              : 111
**             microseconds            : 10
**             seconds (real)          : 0.000010002984
**             Hz                      : 99970
**             kHz                     : 100
**
**         Initialization:
**              Timer                  : Disabled
**
**         Timer registers
**              Counter                : PCNTR0    [0x00150004]
**              Mode                   : PCSR0     [0x00150000]
**              Run                    : PCSR0     [0x00150000]
**              Prescaler              : PCSR0     [0x00150000]
**
**         Compare registers
**              Compare                : PMR0      [0x00150002]
**     Contents    :
**         Enable      - byte SystemTick_Enable(void);
**         Disable     - byte SystemTick_Disable(void);
**         Reset       - byte SystemTick_Reset(void);
**         GetTicks16  - byte SystemTick_GetTicks16(word *Ticks);
**         GetTicks32  - byte SystemTick_GetTicks32(dword *Ticks);
**         GetTicks64  - byte SystemTick_GetTicks64(dlong *Ticks);
**         GetTimeUS   - byte SystemTick_GetTimeUS(word *Time);
**         GetTimeMS   - byte SystemTick_GetTimeMS(word *Time);
**         GetTimeSec  - byte SystemTick_GetTimeSec(word *Time);
**         GetTimeReal - byte SystemTick_GetTimeReal(float *Time);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file SystemTick.h
** @version 01.05
** @brief
**         This device "FreeCntr32" implements 32-bit Free Running Counter
*/         
/*!
**  @addtogroup SystemTick_module SystemTick module documentation
**  @{
*/         

#ifndef __SystemTick_H
#define __SystemTick_H

/* MODULE SystemTick. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "PE_Timer.h"

#include "Cpu.h"



byte SystemTick_Enable(void);
/*
** ===================================================================
**     Method      :  SystemTick_Enable (component FreeCntr32)
*/
/*!
**     @brief
**         This method enables the component - the internal clocks are
**         counted.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
*/
/* ===================================================================*/

byte SystemTick_Disable(void);
/*
** ===================================================================
**     Method      :  SystemTick_Disable (component FreeCntr32)
*/
/*!
**     @brief
**         This method disables the component - the internal clocks are
**         not counted.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
*/
/* ===================================================================*/

byte SystemTick_Reset(void);
/*
** ===================================================================
**     Method      :  SystemTick_Reset (component FreeCntr32)
*/
/*!
**     @brief
**         This method clears the counter.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
*/
/* ===================================================================*/

byte SystemTick_GetTicks16(word *Ticks);
/*
** ===================================================================
**     Method      :  SystemTick_GetTicks16 (component FreeCntr32)
**     Description :
**         Returns the number (as a 16-bit unsigned integer) of main
**         oscillator ticks since the last reset (usually External osc.,
**         internal osc. if exits and external osc. is disabled).
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Ticks           - A pointer to the returned 16-bit value
**                           in main oscillator ticks
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_OVERFLOW - Software counter overflow\
**                           ERR_MATH - Overflow during evaluation
** ===================================================================
*/

byte SystemTick_GetTicks32(dword *Ticks);
/*
** ===================================================================
**     Method      :  SystemTick_GetTicks32 (component FreeCntr32)
**     Description :
**         Returns the number (as a 32-bit unsigned integer) of main
**         oscillator ticks since the last reset (usually External osc.,
**         internal osc. if exits and external osc. is disabled).
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Ticks           - A pointer to the returned 32-bit value
**                           in main oscillator ticks
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_OVERFLOW - Software counter overflow\
**                           ERR_MATH - Overflow during evaluation
** ===================================================================
*/

byte SystemTick_GetTicks64(dlong *Ticks);
/*
** ===================================================================
**     Method      :  SystemTick_GetTicks64 (component FreeCntr32)
**     Description :
**         Returns the number (as a 64-bit unsigned integer) of main
**         oscillator ticks since the last reset (usually External osc.,
**         internal osc. if exists and external osc. is disabled).
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Ticks           - A pointer to the returned 64-bit value
**                           in main oscillator ticks
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_OVERFLOW - Software counter overflow\
**                           ERR_MATH - Overflow during evaluation
** ===================================================================
*/

byte SystemTick_GetTimeUS(word *Time);
/*
** ===================================================================
**     Method      :  SystemTick_GetTimeUS (component FreeCntr32)
**     Description :
**         Returns the time (as a 16-bit unsigned integer) in microseconds
**         since the last resetting after the last reset.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Time            - A pointer to the returned 16-bit value
**                           in microseconds
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_OVERFLOW - Software counter overflow
**                           ERR_MATH - Overflow during evaluation
** ===================================================================
*/

byte SystemTick_GetTimeMS(word *Time);
/*
** ===================================================================
**     Method      :  SystemTick_GetTimeMS (component FreeCntr32)
**     Description :
**         Returns the time (as a 16-bit unsigned integer) in milliseconds
**         since the last resetting after the last reset.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Time            - A pointer to the returned 16-bit value
**                           in milliseconds
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_OVERFLOW - Software counter overflow
**                           ERR_MATH - Overflow during evaluation
** ===================================================================
*/

byte SystemTick_GetTimeSec(word *Time);
/*
** ===================================================================
**     Method      :  SystemTick_GetTimeSec (component FreeCntr32)
**     Description :
**         Returns the time (as a 16-bit unsigned integer) in seconds
**         since the last resetting after the last reset.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Time            - A pointer to the returned 16-bit value
**                           in seconds
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_OVERFLOW - Software counter overflow
**                           ERR_MATH - Overflow during evaluation
** ===================================================================
*/

byte SystemTick_GetTimeReal(float *Time);
/*
** ===================================================================
**     Method      :  SystemTick_GetTimeReal (component FreeCntr32)
**     Description :
**         Returns the time in seconds since the last resetting
**         as a real (floating point) number.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Time            - A pointer to the returned floating
**                           point value in seconds
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_OVERFLOW - Software counter overflow
**                           ERR_MATH - Overflow during evaluation
** ===================================================================
*/

void SystemTick_Init(void);
/*
** ===================================================================
**     Method      :  SystemTick_Init (component FreeCntr32)
**
**     Description :
**         Initializes the associated peripheral(s) and the component 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

void SystemTick_Interrupt(void);
/*
** ===================================================================
**     Method      :  SystemTick_Interrupt (component FreeCntr32)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes event(s) of the component.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

/* END SystemTick. */

#endif 
/* ifndef __SystemTick_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale MCF series of microcontrollers.
**
** ###################################################################
*/
