/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : SystemTick.c
**     Project     : v40.4.5.7_IN3UP
**     Processor   : MCF52233CAF60
**     Component   : FreeCntr32
**     Version     : Component 02.070, Driver 01.05, CPU db: 3.00.000
**     Compiler    : CodeWarrior MCF C Compiler
**     Date/Time   : 2026-06-11, 12:54, # CodeGen: 13
**     Abstract    :
**         This device "FreeCntr32" implements 32-bit Free Running Counter
**     Settings    :
**         Timer name                  : PIT0 (16-bit)
**         Compare name                : PIT0_Modulus
**         Counter shared              : No
**
**         High speed mode
**             Prescaler               : divide-by-1
**             Clock                   : 29491200 Hz
**           Resolution of timer
**             Xtal ticks              : 111
**             microseconds            : 10
**             seconds (real)          : 0.000010002984
**             Hz                      : 99970
**             kHz                     : 100
**
**         Initialization:
**              Timer                  : Disabled
**
**         Timer registers
**              Counter                : PCNTR0    [0x00150004]
**              Mode                   : PCSR0     [0x00150000]
**              Run                    : PCSR0     [0x00150000]
**              Prescaler              : PCSR0     [0x00150000]
**
**         Compare registers
**              Compare                : PMR0      [0x00150002]
**     Contents    :
**         Enable      - byte SystemTick_Enable(void);
**         Disable     - byte SystemTick_Disable(void);
**         Reset       - byte SystemTick_Reset(void);
**         GetTicks16  - byte SystemTick_GetTicks16(word *Ticks);
**         GetTicks32  - byte SystemTick_GetTicks32(dword *Ticks);
**         GetTicks64  - byte SystemTick_GetTicks64(dlong *Ticks);
**         GetTimeUS   - byte SystemTick_GetTimeUS(word *Time);
**         GetTimeMS   - byte SystemTick_GetTimeMS(word *Time);
**         GetTimeSec  - byte SystemTick_GetTimeSec(word *Time);
**         GetTimeReal - byte SystemTick_GetTimeReal(float *Time);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file SystemTick.c
** @version 01.05
** @brief
**         This device "FreeCntr32" implements 32-bit Free Running Counter
*/         
/*!
**  @addtogroup SystemTick_module SystemTick module documentation
**  @{
*/         

/* MODULE SystemTick. */

#include "SystemTick.h"

static bool EnUser;                    /* Enable/Disable device by user */
static dword TTicks;                   /* Counter of timer ticks */
static dword LTicks;                   /* Working copy of variable TTicks */
static bool TOvf;                      /* Counter overflow flag */
static bool LOvf;                      /* Working copy of variable TOvf */

/* Internal method prototypes */
static void HWEnDi(void);
static void LoadTicks(void);

/*
** ===================================================================
**     Method      :  SystemTick_Enable (component FreeCntr32)
*/
/*!
**     @brief
**         This method enables the component - the internal clocks are
**         counted.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
*/
/* ===================================================================*/
byte SystemTick_Enable(void)
{
  if (!EnUser) {                       /* Is the device disabled by user? */
    EnUser = TRUE;                     /* If yes then set the flag "device enabled" */
    HWEnDi();                          /* Enable the device */
  }
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  SystemTick_Disable (component FreeCntr32)
*/
/*!
**     @brief
**         This method disables the component - the internal clocks are
**         not counted.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
*/
/* ===================================================================*/
byte SystemTick_Disable(void)
{
  if (EnUser) {                        /* Is the device enabled by user? */
    EnUser = FALSE;                    /* If yes then set the flag "device disabled" */
    HWEnDi();                          /* Disable the device */
  }
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  SystemTick_Reset (component FreeCntr32)
*/
/*!
**     @brief
**         This method clears the counter.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
*/
/* ===================================================================*/
byte SystemTick_Reset(void)
{
  EnterCritical();                     /* Disable global interrupts */
  setReg16(PMR0,getReg16(PMR0));       /* Reset counter register */
  TTicks =  0;                         /* Reset counter of timer ticks */
  TOvf = FALSE;                        /* Reset counter overflow flag */
  ExitCritical();                      /* Enable global interrupts */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  SystemTick_GetTicks16 (component FreeCntr32)
**     Description :
**         Returns the number (as a 16-bit unsigned integer) of main
**         oscillator ticks since the last reset (usually External osc.,
**         internal osc. if exits and external osc. is disabled).
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Ticks           - A pointer to the returned 16-bit value
**                           in main oscillator ticks
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_OVERFLOW - Software counter overflow\
**                           ERR_MATH - Overflow during evaluation
** ===================================================================
*/
byte SystemTick_GetTicks16(word *Ticks)
{
  dlong rtmul = 0;                     /* Result of two 32-bit numbers multiplication */

  LoadTicks();                         /* Load actual state of counter */
  if (LOvf) {                          /* Testing counter overflow */
    return ERR_OVERFLOW;               /* If yes then error */
  }
  rtmul = (dlong)LTicks * 0x6FUL;      /* Multiply ticks and high speed CPU mode coefficient */
  if (PE_Timer_LngHi0(rtmul,Ticks)) {  /* Is the result greater or equal than 65536 ? */
    return ERR_MATH;                   /* If yes then error */
  }
  else {                               /* Is the result less than 65536 ? */
    return ERR_OK;                     /* If yes then OK */
  }
}

/*
** ===================================================================
**     Method      :  SystemTick_GetTicks32 (component FreeCntr32)
**     Description :
**         Returns the number (as a 32-bit unsigned integer) of main
**         oscillator ticks since the last reset (usually External osc.,
**         internal osc. if exits and external osc. is disabled).
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Ticks           - A pointer to the returned 32-bit value
**                           in main oscillator ticks
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_OVERFLOW - Software counter overflow\
**                           ERR_MATH - Overflow during evaluation
** ===================================================================
*/
byte SystemTick_GetTicks32(dword *Ticks)
{
  dlong rtmul = 0;                     /* Result of two 32-bit numbers multiplication */

  LoadTicks();                         /* Load actual state of counter */
  if (LOvf) {                          /* Testing counter overflow */
    return ERR_OVERFLOW;               /* If yes then error */
  }
  rtmul = (dlong)LTicks * 0x6FUL;      /* Multiply ticks and high speed CPU mode coefficient */
  if (PE_Timer_LngHj0(rtmul,Ticks)) {  /* Is the result greater or equal than 4294967296 ? */
    return ERR_MATH;                   /* If yes then error */
  }
  else {                               /* Is the result less than 4294967296 ? */
    return ERR_OK;                     /* If yes then OK */
  }
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  SystemTick_GetTicks64 (component FreeCntr32)
**     Description :
**         Returns the number (as a 64-bit unsigned integer) of main
**         oscillator ticks since the last reset (usually External osc.,
**         internal osc. if exists and external osc. is disabled).
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Ticks           - A pointer to the returned 64-bit value
**                           in main oscillator ticks
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_OVERFLOW - Software counter overflow\
**                           ERR_MATH - Overflow during evaluation
** ===================================================================
*/
byte SystemTick_GetTicks64(dlong *Ticks)
{
  LoadTicks();                         /* Load actual state of counter */
  if (LOvf) {                          /* Testing counter overflow */
    return ERR_OVERFLOW;               /* If yes then error */
  }
  *Ticks = (dlong)LTicks * 0x6FUL;     /* Multiply ticks and high speed CPU mode coefficient */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  SystemTick_GetTimeUS (component FreeCntr32)
**     Description :
**         Returns the time (as a 16-bit unsigned integer) in microseconds
**         since the last resetting after the last reset.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Time            - A pointer to the returned 16-bit value
**                           in microseconds
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_OVERFLOW - Software counter overflow
**                           ERR_MATH - Overflow during evaluation
** ===================================================================
*/
byte SystemTick_GetTimeUS(word *Time)
{
  dlong rtmul = 0;                     /* Result of two 32-bit numbers multiplication */

  LoadTicks();                         /* Load actual state of counter */
  if (LOvf) {                          /* Testing counter overflow */
    return ERR_OVERFLOW;               /* If yes then error */
  }
  rtmul = (dlong)LTicks * 0x0A00C38EUL; /* Multiply ticks and high speed CPU mode coefficient */
  if (PE_Timer_LngHi3(rtmul,Time)) {   /* Is the result greater or equal than 65536 ? */
    return ERR_MATH;                   /* If yes then error */
  }
  else {                               /* Is the result less than 65536 ? */
    return ERR_OK;                     /* If yes then OK */
  }
}

/*
** ===================================================================
**     Method      :  SystemTick_GetTimeMS (component FreeCntr32)
**     Description :
**         Returns the time (as a 16-bit unsigned integer) in milliseconds
**         since the last resetting after the last reset.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Time            - A pointer to the returned 16-bit value
**                           in milliseconds
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_OVERFLOW - Software counter overflow
**                           ERR_MATH - Overflow during evaluation
** ===================================================================
*/
byte SystemTick_GetTimeMS(word *Time)
{
  dlong rtmul = 0;                     /* Result of two 32-bit numbers multiplication */

  LoadTicks();                         /* Load actual state of counter */
  if (LOvf) {                          /* Testing counter overflow */
    return ERR_OVERFLOW;               /* If yes then error */
  }
  rtmul = (dlong)LTicks * 0x028F8E39UL; /* Multiply ticks and high speed CPU mode coefficient */
  if (PE_Timer_LngHi4(rtmul,Time)) {   /* Is the result greater or equal than 65536 ? */
    return ERR_MATH;                   /* If yes then error */
  }
  else {                               /* Is the result less than 65536 ? */
    return ERR_OK;                     /* If yes then OK */
  }
}

/*
** ===================================================================
**     Method      :  SystemTick_GetTimeSec (component FreeCntr32)
**     Description :
**         Returns the time (as a 16-bit unsigned integer) in seconds
**         since the last resetting after the last reset.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Time            - A pointer to the returned 16-bit value
**                           in seconds
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_OVERFLOW - Software counter overflow
**                           ERR_MATH - Overflow during evaluation
** ===================================================================
*/
byte SystemTick_GetTimeSec(word *Time)
{
  dlong rtmul = 0;                     /* Result of two 32-bit numbers multiplication */

  LoadTicks();                         /* Load actual state of counter */
  if (LOvf) {                          /* Testing counter overflow */
    return ERR_OVERFLOW;               /* If yes then error */
  }
  rtmul = (dlong)LTicks * 0xA7D27D28UL; /* Multiply ticks and high speed CPU mode coefficient */
  if (PE_Timer_LngHi6(rtmul,Time)) {   /* Is the result greater or equal than 65536 ? */
    return ERR_MATH;                   /* If yes then error */
  }
  else {                               /* Is the result less than 65536 ? */
    return ERR_OK;                     /* If yes then OK */
  }
}

/*
** ===================================================================
**     Method      :  SystemTick_GetTimeReal (component FreeCntr32)
**     Description :
**         Returns the time in seconds since the last resetting
**         as a real (floating point) number.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Time            - A pointer to the returned floating
**                           point value in seconds
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_OVERFLOW - Software counter overflow
**                           ERR_MATH - Overflow during evaluation
** ===================================================================
*/
byte SystemTick_GetTimeReal(float *Time)
{
  LoadTicks();                         /* Load actual state of counter */
  if (LOvf) {                          /* Testing counter overflow */
    return ERR_OVERFLOW;               /* If yes then error */
  }
  *Time = (float)LTicks * 0.000010002984F; /* Multiply ticks and high speed CPU mode coefficient */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  SystemTick_Init (component FreeCntr32)
**
**     Description :
**         Initializes the associated peripheral(s) and the component 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void SystemTick_Init(void)
{
  /* PCSR0: ??=0,??=0,??=0,??=0,PRE=0,??=0,DOZE=0,DBG=0,OVW=1,PIE=1,PIF=1,RLD=1,EN=0 */
  setReg16(PCSR0, 0x1EU);              /* Set up control register */ 
  TTicks = 0;                          /* Counter of timer ticks */
  TOvf = FALSE;                        /* Counter overflow flag */
  EnUser = FALSE;                      /* Disable device */
  /* PMR0: PM=0x0126 */
  setReg16(PMR0, 0x0126U);             /* Store given value to the modulus register */ 
  HWEnDi();                            /* Enable/disable device according to status flags */
}

/*
** ===================================================================
**     Method      :  SystemTick_Interrupt (component FreeCntr32)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes event(s) of the component.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
__declspec(interrupt) void SystemTick_Interrupt(void)
{
  setReg16Bit(PCSR0,PIF);              /* Reset interrupt request flag */
  TTicks++;                            /* Increment counter of timer ticks */
  if (TTicks == 0) {                   /* Testing counter overflow */
    TOvf = TRUE;                       /* If yes then set overflow flag */
  }
}

/*
** ===================================================================
**     Method      :  LoadTicks (component FreeCntr32)
**
**     Description :
**         Loads actual number of timer ticks from internal variable. The 
**         method is called automatically as a part of several internal 
**         methods.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static void LoadTicks(void)
{
  EnterCritical();                     /* Disable global interrupts */
  LTicks = TTicks;                     /* Loading actual number of timer ticks */
  LOvf = TOvf;                         /* Loading actual state of "overflow flag" */
  ExitCritical();                      /* Enable global interrupts */
}

/*
** ===================================================================
**     Method      :  HWEnDi (component FreeCntr32)
**
**     Description :
**         Enables or disables the peripheral(s) associated with the 
**         component. The method is called automatically as a part of the 
**         Enable and Disable methods and several internal methods.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static void HWEnDi(void)
{
  if (EnUser) {                        /* Enable device? */
    setReg16Bit(PCSR0,EN);             /* Run counter */
  }
  else {                               /* Disable device? */
    clrReg16Bit(PCSR0,EN);             /* Stop counter */
  }
}

/* END SystemTick. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale MCF series of microcontrollers.
**
** ###################################################################
*/
